### PR TITLE
Add buildtool and exec depends on python3 for packaging.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Needed to build properly on the ROS 2 testfarm.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am not convinced that we should add dependencies in Python 3 for all packages which contain Python code.

**Comment by nuclearsandwich** [comment]
> I am not convinced that we should add dependencies on Python 3 for all packages which contain Python code.

I'm open to alternatives, I've been preferring low-effort, low-touch solutions wherever possible. These changes have so far been necessary for debhelper to work correctly with ament_python packages. I'm open to other suggestions. Any python package in a system package manager depends on python and this mirrors that situation.

**Comment by wjwwood** [comment]
> I am not convinced that we should add dependencies on Python 3 for all packages which contain Python code.

What should we do instead?

**Comment by dirk-thomas** [comment]
> > I am not convinced that we should add dependencies on Python 3 for all packages which contain Python code.

> What should we do instead?

I don't have answer at hand. But we e.g. also don't declare `build-essential` as a build dependency in our manifest files.

**Comment by dirk-thomas** [comment]
Once ros2/ros2#358 has been merged I will close this PR and also delete this repo. I hope the dependencies in the new repo https://github.com/ros2/ros2cli are already ok - maybe they need similar changes as proposed in this PR.

**Comment by dirk-thomas** [comment]
Closing this since we won't build binary packages of the code in this repo anymore but for the new packages in https://github.com/ros2/ros2cli instead.

**Pull request closed without merging**
